FROM rails:4.2.1
MAINTAINER wzdxt <wzdxt0624@gmail.com>

WORKDIR /root
RUN wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz && \
  tar xvf ffmpeg-release-64bit-static.tar.xz && \
  ln -s /root/ffmpeg-2.6.3-64bit-static/ffmpeg /usr/bin/ffmpeg && \
  rm ffmpeg-release-64bit-static.tar.xz && \
  apt-get update && \
  apt-get install -y graphicsmagick && \
  apt-get install -y mkvtoolnix && \
  apt-get install -y libgtkmm-3.0-1 && \
  apt-get install -y libnotify4 && \
  rm -rf /var/lib/apt/lists/*

EXPOSE 3000

