production:
  server:
    web_server:
      main:
        hostname: main-server
        address: http://wgcloud.com
    upload_server:
      ups1:
        hostname: ups1
        address: http://upload.wgcloud.com
    video_server:
      video1:
        hostname: video
        address: http://video.wgcloud.com

development:
  server:
    web_server:
      main:
        hostname: main
        address: http://localhost:3000
    upload_server:
      upload:
        hostname: upload
        address: http://localhost:3000
    video_server:
      video:
        hostname: video
        address: http://localhost:3000

test: