log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      trace     : 'false'
      outputters :
      - rollingfile
    - name      : development
      trace     : 'true'
      outputters :
      - rollingfile
      - std

  # define all outputters (incl. formatters)
  outputters:
  - type: RollingFileOutputter
    name: rollingfile
    level: DEBUG
    filename: "log/15class.log"
    maxsize: 100,000,000
    formatter:
      type        : PatternFormatter
      date_pattern: '%Y-%m-%d %H:%M:%S'
      pattern     : "%d [%5l] [%T]: %M"
  - type: StdoutOutputter
    name: std
    level: INFO
    formatter:
      type: PatternFormatter
      date_pattern: '%Y-%m-%d %H:%M:%S'
      pattern     : "%d [%5l] [%T]: %M"


